# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d5ba406c20b6cdfa3f07e707fcb010bf58cb15facda354ce5c68be1a6cd20e52ff54dac11db62bf895f83448efaf6153614e0e0e365c55bb39338a18c3638f5a

test:
  secret_key_base: 01d179c71badc9a6355c910de43e5b72c7b41c7ec0e550bd2d25314b106478e6a3d5635bcae2711399f2fcc286267910842e8100a07343954e86ca03bbb41745

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
